version: "3"
services:
  #Laravel App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: content-dev/laravel
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8181:8181"
    env_file: .env
    depends_on:
      - db
    networks:
      - mynet
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=root@clane
      - MYSQL_DATABASE=articles
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynet

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root@clane
    networks:
      - mynet

#Docker Networks
networks:
  mynet:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local
